### ISSUE TITLE
Switch Google Fusion Table To Dedicated UIL Account

### ISSUE THREAD

**Issue by cbischak** [JianweiCxyz/UIL_webpages#13]
Switch Google Fusion stuff to dedicated UIL account. Nonessential for soft launch on Monday

**Comment by JianweiCxyz** [comment]
OK, Please e-mail me the account info.

**Comment by cbischak** [comment]
@JianweiCxyz can we close this issue? Yes right?

**Comment by JianweiCxyz** [comment]
Sure.
