### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by JianweiCxyz** [JianweiCxyz/UIL_webpages#2]
Desktop
- Firefox: all fine.
- Chrome: all fine.
- IE: cannot display legends
- Edge: cannot display legends

Mobile (ios)
- Safari / Chrome: cannot display maps

Mobile (Android)
- Unknown

**Comment by JianweiCxyz** [comment]
Legends fixed.

**Comment by cbischak** [comment]
Android has sizing/scaling issues

**Comment by JianweiCxyz** [comment]
Fixed with https://github.com/JianweiCxyz/UIL_webpages/commit/c16948b514cd60c07872530a4d26c9bc60335f57

**Comment by JianweiCxyz** [comment]
@cbischak  See if Android works.

**Comment by JianweiCxyz** [comment]
@cbischak  Check this link: http://utw10792.utweb.utexas.edu/test3/ on Android.

**Comment by cbischak** [comment]
Works fine on Android. Closing for now as this issue has been fixed sufficiently for soft launch.

**Comment by cbischak** [comment]
Android has issues with latest version. The header runs over on to over parts of the page.

**Comment by JianweiCxyz** [comment]
This issue is temporally fixed by https://github.com/JianweiCxyz/UIL_webpages/commit/37d595dbe6334c79e8e4d67b74a030ca2c89e0a8

I hide the LOGO in phone size screens. Let me know if you think hiding title is better.

**Comment by JianweiCxyz** [comment]
Fixed with b69b446
