### ISSUE TITLE
Color scheme and transparency

### ISSUE THREAD

**Issue by JianweiCxyz** [JianweiCxyz/UIL_webpages#3]

**Comment by cbischak** [comment]
Use the following colors for the map: 

#979B95 = Neutral
#63A500 = Oasis 
#B22F07 = Desert 

Set transparency to 40%. Do you want me to handle this through the KML File or will you do it on the CSV file end?

**Comment by JianweiCxyz** [comment]
I'll handle them~

**Comment by cbischak** [comment]
Should be fixed with new KML file once that is added to Fusion table

**Comment by JianweiCxyz** [comment]
Fixed http://utw10792.utweb.utexas.edu/test4/
