### ISSUE TITLE
Add Pitt Additional Data to Map

### ISSUE THREAD

**Issue by cbischak** [JianweiCxyz/UIL_webpages#30]
# @JianweiCxyz how should we do this? Should I use add the Pitt data to the Access DB or should I send you like an excel file with the data? Thanks

**Comment by JianweiCxyz** [comment]
Excell is OK.

**Comment by cbischak** [comment]
Ok. I'll send it over in a bit.

**Comment by JianweiCxyz** [comment]
Is it has map but with no z-score etc. ?

**Comment by JianweiCxyz** [comment]
You can send me access db's Master_Files exported csv. That would be fastest.

**Comment by cbischak** [comment]
@JianweiCxyz check the UIL Google Drive. There is an Excel File with all the data now. Thanks.

**Comment by JianweiCxyz** [comment]
Done.
