### ISSUE TITLE
LOGO too small

### ISSUE THREAD

**Issue by JianweiCxyz** [JianweiCxyz/UIL_webpages#4]

**Comment by cbischak** [comment]
Don't fix this yet. I have a new commit I'm working on that will add a new logo etc. Wait until I upload the newer logo.

**Comment by JianweiCxyz** [comment]
Sure.

**Comment by JianweiCxyz** [comment]
Temporally fixed. PNG file is too big. @cbischak  Could you send me the pdf file, I'll convert it to svg and embed it.

**Comment by cbischak** [comment]
Yes I will email you this.

**Comment by JianweiCxyz** [comment]
Fixed with smaller png. 
Hao's laptop stolen, may recover a svg later.
