### ISSUE TITLE
Add Google Analytics to the website

### ISSUE THREAD

**Issue by JianweiCxyz** [JianweiCxyz/UIL_webpages#7]

**Comment by JianweiCxyz** [comment]
Analytics script added. Will have to wait until the website is online to test.

**Comment by cbischak** [comment]
What email/Google account did you use to do this? I think we need a dedicated gmail account that we can use for this

**Comment by JianweiCxyz** [comment]
You made a good point, I'll fix it later.

**Comment by cbischak** [comment]
I have a dedicated mail I made for the lab. I will update this later or email you the info.

**Comment by cbischak** [comment]
Should be fixed with latest pull request. Now on a dedicated UIL email address
